services:
    es:
        image: elasticsearch:9.0.1
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        volumes:
            - es-data:/usr/share/elasticsearch/data

    kibana:
        image: kibana:9.0.1
        ports:
            - "5601:5601"
        environment:
            - ELASTICSEARCH_HOSTS=http://es:9200

volumes:
    es-data:
        driver: local
